#!/usr/bin/env ruby
# frozen_string_literal: true

title = "ruby #{ARGV * ' '}"
$0    = ARGV.shift
Process.setproctitle(title) if Process.methods.include?(:setproctitle)

require 'rubygems'
unless $PROGRAM_NAME.end_with?('/executable-hooks-uninstaller')
  begin
    require 'executable-hooks/hooks'
    Gem::ExecutableHooks.run($PROGRAM_NAME)
  rescue LoadError
    warn 'unable to load executable-hooks/hooks' if ENV.key?('ExecutableHooks_DEBUG')
  end
end

content = File.read($PROGRAM_NAME)

if (index = content.index("\n#!ruby\n")) && index.positive?
  skipped_content = content.slice!(0..index)
  start_line = skipped_content.count("\n") + 1
  eval content, binding, $PROGRAM_NAME, start_line
else
  eval content, binding, $PROGRAM_NAME
end
